### ISSUE TITLE
Some MIDIs are way too loud.

### ISSUE THREAD

**Issue by thegreatestminer** [KaleidonKep99/Keppys-MIDI-Converter#24]
Some of the MIDIs I converted to OGG are quite loud. Is it possible to add a volume mixer, or a dB limiter?

Attached is the original MIDI, and the rendered MIDI in OGG format. (compressed into ZIP because GitHub doesn't allow MIDIs)

Soundfonts used (in order):
Keppy's Steinway Piano v6.03 (October 2, 2016)
Timbres of Heaven GM v3.2 Final

[midi.zip](https://github.com/KaleidonKep99/Keppys-MIDI-Converter/files/693389/midi.zip)

EDIT: Obligatory Audacity pic:
![2017-01-09_07-23-06](https://cloud.githubusercontent.com/assets/19188146/21766437/92cddf7e-d63c-11e6-8606-ae97ebd3507a.png)

**Comment by KaleidonKep99** [comment]
There's a reason why I added VST effects support to KMC! Haha! 😆
You can use LoudMax with it: http://loudmax.blogspot.com/

You can load it by going to **"Actions > Open the soundfonts/VST manager > Check 'I want to apply a VST DSP too...' > Click 'Open the VST DSP manager'", then click "Load" on one of the slots.

Be sure to get the right version for KMC, since the 32-bit version will **NOT** work with KMC 64-bit.

**Comment by thegreatestminer** [comment]
Neat, will try that a little later. Thanks!

**Comment by KaleidonKep99** [comment]
Okay, tell me if it does what you wanted.
I'll keep the issue open.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
