### ISSUE TITLE
Add Controller 111 MIDI Loop Start event + Loop X times

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/Keppys-MIDI-Converter#4]
It would be nice if we have a "Loop X times" option, even for MIDI files that have controller 111 when a song reaches to the end X times jump to that "loop start" spot instead of going back to the beginning, or MIDI files without controller 111 when a song reaches to the end loop X times to the beginning.

[Example of a MIDI file with the Controller 111 loop.](http://googledrive.com/host/0B_hEYwlKhaY-fmdndlpfNkl6SU9JU043TDd2SThMRU1sV245REVSUUNERnh1cFpqOVFJVVk/Kirby%2064%20-%20Game%20Over.mid)

**Comment by KaleidonKep99** [comment]
You should make a post about that in the [Un4seen's official forum] (http://www.un4seen.com/forum/?board=1.0).

I have no control in the BASS libraries, only Ian Luck does.

**Comment by Wohlstand** [comment]
libADLMIDI (unlike BASS, it using emulated OPL-3 Synthesiser to play MIDI's with hardcoded banks which makes it be multiplatform and be independent. However sound is electronic-only, but it may be beutful) in my control, but by default it uses Final Fantasy VII way to loop MIDI's (via "loopStart" and "loopEnd" tags), so, I think, I'll try to add this, because I also asked by someone to add same controller support. Only one question: what to do if multiple of them? I can:
* Just ignore all next 111'th controllers if one of defined at begin
* next 111'th controller will declare loopEnd

**Comment by DevanWolf** [comment]
Of course controller 112 would be loop end.

**Comment by Wohlstand** [comment]
Seems not optional since every controller can have one byte of any data (in total from 0 to 255 of unsigned data or -127 to 127 of signed)
